version: '3.6'

services:

    redmine:
        build: .    
        ports:
        - 8080:3000
        environment:
            RAILS_ENV: development
        volumes:
        - redmine-sqlite:/usr/src/redmine/sqlite/
        - $PWD:/usr/src/redmine/plugins/redmine_issue_dependency_graph/

volumes:
  redmine-sqlite:           

